services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/usr/src/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - app
